name: Build and Push Container

on:
  workflow_call:
    inputs:
      container_name:
        required: true
        type: string
      platforms:
        type: string
        default: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Check pyproject.toml
        id: check_pyproject
        uses: andstor/file-existence-action@v2
        with:
          files: "pyproject.toml"

      - name: Install poetry
        if: steps.check_pyproject.outputs.files_exists == 'true'
        run: |
          python -m pip install pip wheel pipx --upgrade
          pipx install poetry

      - name: Export Poetry Requirements
        if: steps.check_pyproject.outputs.files_exists == 'true'
        run: poetry export -o requirements.txt

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Github CR Login
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Date
        run: echo "DATE_TAG=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - name: Build Container
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/bellflight/avr/${{ inputs.container_name }}:latest
            ghcr.io/bellflight/avr/${{ inputs.container_name }}:${{ env.DATE_TAG }}
          platforms: ${{ inputs.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
